networks:
    laram:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: olx_nginx
        ports:
            - "8000:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/certs/cert.crt:/etc/nginx/cert.crt
            - ./.docker/certs/cert.key:/etc/nginx/cert.key
        depends_on:
            - php
            - mysql
            - redis
        networks:
            - laram

    mysql:
        image: 'mysql:8'
        container_name: olx_mysql
        ports:
            - "33062:3306"
        restart: always
        command: --pid-file /var/lib/mysql/mysqld.pid --local-infile=1
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_DATABASE: 'olx'
            MYSQL_USER: 'olx'
            MYSQL_PASSWORD: 'secret'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - mydb:/var/lib/mysql
        networks:
            - laram
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-psecret"]
            retries: 3
            timeout: 5s

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: olx_pma
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        depends_on:
            - php
            - mysql
        ports:
            - "8083:80"
        networks:
            - laram

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: olx_php
        volumes:
            - ./:/var/www/html
        ports:
            - "9001:9001"
        networks:
            - laram

    redis:
        image: "redis:alpine"
        container_name: olx_redis
        ports:
            - "63791:6379"
        networks:
            - laram

    composer:
        image: composer:latest
        container_name: olx_composer
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - php
        networks:
            - laram

    npm:
        image: node:18
        container_name: olx_npm
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']

    artisan:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: olx_artisan
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
            - redis
        working_dir: /var/www/html
        entrypoint: ['php','/var/www/html/artisan']
        networks:
            - laram

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: olx_cp
        volumes:
            - ./:/var/www/html
        depends_on:
            - mysql
            - redis
        working_dir: /var/www/html
        networks:
            - laram


#Volumes
volumes:
    mydb:
        driver: local
